theme = "omarchy"

[editor]
end-of-line-diagnostics = "hint"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[keys.normal.space]
g = [ ":write-all", ":insert-output ldf >/dev/tty", ":redraw", ":reload-all" ]
