theme = "omarchy"

[editor]
line-number = "relative"
popup-border = "all"
end-of-line-diagnostics = "hint"
true-color = true

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[keys.normal.space]
g = [ ":write-all", ":insert-output ldf >/dev/tty", ":redraw", ":reload-all" ]

